import { Metadata } from "next"
export const metadata : Metadata = {
  title: {
    default:"Usman",
    template:"%s | usman"
  },
  description: 'Generated by Next.js',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <nav>Header</nav>
        {children}
        <footer>footer</footer>
        </body>
    </html>
  )
}
